## ============ SERVER ============
ang: ## Launch Angular local server
	ng serve -o
.PHONY: ang


## ============ INSTALL ============
install: ## Install all composants and dependencies after a clone repository
	npm install @fortawesome/fontawesome-svg-core
	npm install @fortawesome/free-solid-svg-icons
	npm install @fortawesome/free-brands-svg-icons
	npm install @fortawesome/angular-fontawesome@0.10.x
	ng add @angular/material
	npm i animate.css
	npm install -g @compodoc/compodoc

	npm i jwt-decode
	npm i ngx-pagination
.PHONY: install