api_platform:
    title: 'EasyGarden API'
    description: 'API to deal with Vue.js'
    version: '1.0'
    # Araignée specs APi_Platform   https://127.0.0.1:8000/api
    show_webby: false
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    # Enable MAX_DEPTH = true
    eager_loading:
        force_eager: false
        fetch_partial: true
    # api_platform:
    #     swagger:
    #         api_keys:
    #             apiKey:
    #             name: Authorization
    #             type: header
    # annotationGenerators:
    #     - ApiPlatform\SchemaGenerator\AnnotationGenerator\SerializerGroupsAnnotationGenerator
